### ISSUE TITLE
Label doesn't appear after a value is selected from dropdown.

### ISSUE THREAD

**Issue by ashwintastic** [RocketSoftware/carbon#11]
Hi Team,

I'm using carbon-component-react dropDown [DropDown link](http://react.carbondesignsystem.com/?path=/story/dropdown--default)

How can I reset the label once I have selected items from drop-down?

Steps to reproduce:

1. Render the drop-down with label say '**Please select**'.
2.Let the drop-down options be _option-1_, _option-2_.
3. Select an option from the dropdown.

Now the label has gone, and the dropdown will have a selected value , how can I deselect the dropdown, or how can I take the dropdown to its initial state where it was having a label and nothing was selected from it, without page refresh.

**Comment by hshockley** [comment]
Hello,
In the storybook, the 'fully controlled' story provides an example of using state to control which item is currently selected. You might be able to reset the state by setting the state.selectedItem to null from a child element. By the logic of the label it would then be visible again.
